package sqld

import (
	"context"
	"fmt"
	"os"
	"os/exec"
)

// Runner wraps the sqld binary so callers don't have to think about
// resolution, env, or stdio plumbing. It's the spiritual replacement for
// internal/litestream/runner.go's Runner type.
type Runner struct {
	binPath string
}

// NewRunner resolves the sqld binary (bundled or PATH).
func NewRunner() (*Runner, error) {
	bin, err := Resolve()
	if err != nil {
		return nil, err
	}
	return &Runner{binPath: bin}, nil
}

// PrimaryOpts configures sqld in primary-server mode: serves Hrana to apps,
// gRPC to replicas, and replicates WAL frames to the user's bucket via
// bottomless.
type PrimaryOpts struct {
	// DBPath is the local SQLite file sqld manages. Apps read/write here
	// (or via Hrana over HTTP — both views are kept in sync by sqld).
	DBPath string

	// HTTPListenAddr exposes sqld's HTTP API (Hrana over HTTP fallback +
	// REST endpoints). Default upstream is 127.0.0.1:8080.
	HTTPListenAddr string

	// HranaListenAddr exposes Hrana over WebSocket — preferred client
	// transport. Optional; if empty, only HTTP is exposed.
	HranaListenAddr string

	// GRPCListenAddr is where replica nodes connect to stream WAL frames.
	// Should be reachable over the private network or VPN. If empty,
	// no replicas can attach (primary-only deployment).
	GRPCListenAddr string

	// AdminListenAddr is where `sqlitedeploy status` queries replication
	// state. Bind to localhost only; not for client traffic.
	AdminListenAddr string

	// AuthJWTKeyFile is the PEM path to the Ed25519 *public* key sqld uses
	// to verify JWTs presented by clients and replicas. Generated by
	// `sqlitedeploy init`. Leaving this empty disables auth — fine for
	// local dev, NEVER for production.
	AuthJWTKeyFile string

	// BottomlessEnv carries the LIBSQL_BOTTOMLESS_* vars produced by
	// BottomlessEnv(). Keep separate from process env so we don't leak
	// other env vars accidentally.
	BottomlessEnv map[string]string
}

// Serve runs sqld in primary mode until ctx is cancelled or the process
// exits. Stdio is plumbed to the parent so users see sqld's logs in their
// terminal — same UX as the previous Litestream `replicate` daemon.
func (r *Runner) Serve(ctx context.Context, opts PrimaryOpts) error {
	if opts.DBPath == "" {
		return fmt.Errorf("sqld.Serve: DBPath required")
	}
	args := []string{
		"--db-path", opts.DBPath,
		"--enable-bottomless-replication",
	}
	if opts.HTTPListenAddr != "" {
		args = append(args, "--http-listen-addr", opts.HTTPListenAddr)
	}
	if opts.HranaListenAddr != "" {
		args = append(args, "--hrana-listen-addr", opts.HranaListenAddr)
	}
	if opts.GRPCListenAddr != "" {
		args = append(args, "--grpc-listen-addr", opts.GRPCListenAddr)
	}
	if opts.AdminListenAddr != "" {
		args = append(args, "--admin-listen-addr", opts.AdminListenAddr)
	}
	if opts.AuthJWTKeyFile != "" {
		args = append(args, "--auth-jwt-key-file", opts.AuthJWTKeyFile)
	}

	cmd := exec.CommandContext(ctx, r.binPath, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	cmd.Env = mergeEnv(os.Environ(), opts.BottomlessEnv)
	return cmd.Run()
}

// ReplicaOpts configures sqld in replica mode: streams WAL frames from a
// primary over gRPC and serves Hrana locally for read traffic.
type ReplicaOpts struct {
	// DBPath is the local SQLite file sqld keeps in sync. Reads off this
	// file are sub-second fresh; writes are forwarded to the primary.
	DBPath string

	// HTTPListenAddr exposes the local Hrana-over-HTTP endpoint for app
	// reads. Defaults to 127.0.0.1:8080 upstream.
	HTTPListenAddr string

	// HranaListenAddr exposes Hrana-over-WebSocket locally. Optional.
	HranaListenAddr string

	// PrimaryGRPCURL is the primary's gRPC endpoint, e.g.
	// "http://primary.example.com:5001". Required.
	PrimaryGRPCURL string

	// AuthJWTKeyFile is needed both to verify incoming client JWTs (same
	// as primary) and to authenticate to the primary's gRPC. May be the
	// same file deployed to primary and replicas.
	AuthJWTKeyFile string

	// BottomlessEnv is used for cold-start seed: on first run, the replica
	// can pull a snapshot from the bucket via bottomless, then catch up
	// over gRPC. Optional — without it, the replica must replay everything
	// from gRPC, which is slow for large databases.
	BottomlessEnv map[string]string

	// SyncFromStorage tells sqld to seed the local DB from bottomless on
	// startup. Set to true on first attach; false on subsequent runs (the
	// local DB is already populated, faster to skip the bucket pull).
	SyncFromStorage bool
}

// ServeReplica runs sqld in replica mode until ctx is cancelled.
func (r *Runner) ServeReplica(ctx context.Context, opts ReplicaOpts) error {
	if opts.DBPath == "" {
		return fmt.Errorf("sqld.ServeReplica: DBPath required")
	}
	if opts.PrimaryGRPCURL == "" {
		return fmt.Errorf("sqld.ServeReplica: PrimaryGRPCURL required")
	}
	args := []string{
		"--db-path", opts.DBPath,
		"--primary-grpc-url", opts.PrimaryGRPCURL,
	}
	if opts.HTTPListenAddr != "" {
		args = append(args, "--http-listen-addr", opts.HTTPListenAddr)
	}
	if opts.HranaListenAddr != "" {
		args = append(args, "--hrana-listen-addr", opts.HranaListenAddr)
	}
	if opts.AuthJWTKeyFile != "" {
		args = append(args, "--auth-jwt-key-file", opts.AuthJWTKeyFile)
	}
	if opts.SyncFromStorage {
		args = append(args, "--sync-from-storage")
	}

	cmd := exec.CommandContext(ctx, r.binPath, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	env := os.Environ()
	if opts.SyncFromStorage {
		// Bottomless creds only needed if we're seeding from the bucket.
		env = mergeEnv(env, opts.BottomlessEnv)
	}
	cmd.Env = env
	return cmd.Run()
}

// Restore is a stub for fresh-node disaster recovery. The intended
// implementation is `sqld --db-path ... --sync-from-storage` with the
// bottomless env, exited once the local DB has been written.
//
// Phase 4 will flesh this out — likely by running Serve with sync_from_storage
// and detecting completion via the admin API, then cancelling the context.
// Alternatively, bundle `bottomless-cli` separately and invoke its `restore`
// subcommand for a cleaner one-shot UX.
func (r *Runner) Restore(ctx context.Context, dbPath string, env map[string]string) error {
	return fmt.Errorf("sqld.Restore: not yet implemented (Phase 4 work; see comment in runner.go)")
}

// Status is a stub for replication-state introspection. The intended
// implementation hits sqld's admin HTTP API (--admin-listen-addr) for
// metrics like last-replicated-frame and bottomless lag.
func (r *Runner) Status(ctx context.Context, adminAddr string) ([]byte, error) {
	return nil, fmt.Errorf("sqld.Status: not yet implemented (Phase 4 work)")
}

// mergeEnv overlays add onto base; if a key exists in both, add wins.
func mergeEnv(base []string, add map[string]string) []string {
	if len(add) == 0 {
		return base
	}
	idx := make(map[string]int, len(base))
	for i, kv := range base {
		for j := 0; j < len(kv); j++ {
			if kv[j] == '=' {
				idx[kv[:j]] = i
				break
			}
		}
	}
	out := append([]string(nil), base...)
	for k, v := range add {
		entry := k + "=" + v
		if i, ok := idx[k]; ok {
			out[i] = entry
		} else {
			out = append(out, entry)
		}
	}
	return out
}
